repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        files: \.py$
        exclude: ^(.*pb2.*|.*\.pyi)$
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        files: \.py$
        exclude: ^(.*pb2.*|.*\.pyi)$
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        pass_filenames: false
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        exclude: ^(.*pb2.*|.*\.pyi)$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^(tests/.*|examples/.*|docs/.*|.*pb2.*|.*\.pyi)$
